-- Oracle 不支持原生数组类型，使用 JSON/VARCHAR2 列替代
DROP TABLE array_test CASCADE CONSTRAINTS PURGE;
/

CREATE TABLE array_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    int_data VARCHAR2(4000),
    text_data VARCHAR2(4000)
);
/

INSERT INTO array_test (name, int_data, text_data) VALUES ('数组测试', '[1,2,3,4,5]', '["a","b","c"]');
INSERT INTO array_test (name, int_data, text_data) VALUES ('空数组', '[]', '[]');
