DROP TABLE preparedstatement_test CASCADE CONSTRAINTS PURGE;
/

CREATE TABLE preparedstatement_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    value NUMBER,
    amount NUMBER(12,2),
    active NUMBER(1),
    created_at TIMESTAMP,
    updated_at DATE,
    description CLOB,
    data BLOB
);
/
