DROP TABLE resultset_test CASCADE CONSTRAINTS PURGE;
/

CREATE TABLE resultset_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    value NUMBER NOT NULL,
    amount NUMBER(12,2),
    active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE,
    description CLOB,
    data BLOB,
    rating BINARY_DOUBLE,
    status NUMBER(5) DEFAULT 1,
    big_num NUMBER(19)
);
/
