DROP TABLE statement_test CASCADE CONSTRAINTS PURGE;
/

CREATE TABLE statement_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    value NUMBER DEFAULT 0,
    active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE INDEX idx_statement_test_name ON statement_test(name);
/
